# ttt variations

- https://en.wikipedia.org/wiki/Tic-tac-toe_variants

## ultimate tic-tac-toe

- https://en.wikipedia.org/wiki/Ultimate_tic-tac-toe
- https://mathwithbaddrawings.com/2013/06/16/ultimate-tic-tac-toe/

---

## m,n,k-game

- https://en.wikipedia.org/wiki/M,n,k-game


## 3d 

- https://en.wikipedia.org/wiki/3D_tic-tac-toe

## Harary's generalized tic-tac-toe

- https://en.wikipedia.org/wiki/Harary%27s_generalized_tic-tac-toe

## nd game

- https://en.wikipedia.org/wiki/Nd_game



In [12]:
import numpy as np
from pprintpp import pprint as pp

In [6]:
matrix = np.zeros((3,3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
matrix = np.array([[np.zeros((3, 3)) for _ in range(3)] for _ in range(3)], dtype=object)

In [26]:
# Create a 3x3 matrix where each element is a 3x3 matrix
matrix = np.zeros((3, 3, 3, 3))

# Access individual 3x3 matrices
print("Matrix at position [0,0]:")
print(matrix[0, 0])

# print(matrix)

Matrix at position [0,0]:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
matrix = np.zeros((3, 3, 3, 3, 3, 3))
# print(matrix)

In [35]:
_tuple = (3,3)
matrix = np.zeros(_tuple)
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [45]:
_list = []

# 3x3 = 3^2
# 3x3x3x3 = 3^4
# 3x3x3x... = 3^d

n = 3
d = 2 # dimension d must be greater than 2 and must be an even number

for x in range(d):
    _list.append(n)
_tuple = tuple(_list)


print(_tuple)

matrix = np.zeros(_tuple)
print(matrix)

(3, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [54]:
# 3x3 classic tic-tac-toe

class Grid:
    def __init__(self):
        self.n = 3
        self.d = 2 
        self._grid = None
        self.init_grid()

    def init_grid(self):
        _list = []
        for x in range(d):
            _list.append(n)
        _tuple = tuple(_list)
        
        self._grid = np.zeros(_tuple, dtype=int)

    @property
    def grid(self):
        return self._grid

    def place_mark(self, x, y):
        pass

    

In [55]:
grid = Grid()

print(grid.grid)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [56]:
matrix = np.zeros((3,3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [58]:
print(matrix[0][1])

0


In [61]:
matrix[0][1] = 1

print(matrix[0][1])
print(matrix)

1
[[0 1 0]
 [0 0 0]
 [0 0 0]]


In [130]:
# 3^d classic tic-tac-toe

class Grid:
    def __init__(self, d):
        self.n = 3
        self.d = d # must be even and d >= 2
        self._grid = None
        self._score_grid = None
        self.init_grid()

        if self.d > 2 and self.d % 2 == 0:
            self.init_score_grid()
        

    def init_grid(self):
        _list = []
        for x in range(self.d):
            _list.append(3)
        _tuple = tuple(_list)
        
        self._grid = np.zeros(_tuple, dtype=int)

    def init_score_grid(self):
        dimension = self.d - 2
        _list = []
        for x in range(dimension):
            _list.append(3)
        _tuple = tuple(_list)
        
        self._score_grid = np.zeros(_tuple, dtype=int)
        

    @property
    def grid(self):
        return self._grid

    @property
    def score_grid(self):
        return self._score_grid

    def place_mark(self, x, y): # for 3x3
        pass


In [69]:
grid = Grid(6)

# print(grid.grid)
# print(grid.score_grid)



In [164]:
# get turn for players

active_turn = -1

def switch_turn():
    global active_turn
    active_turn *= -1
    return active_turn

def get_player():
    return 0 if active_turn == 1 else 1

In [204]:
print(f"player {get_player()}: {switch_turn()}")

player 0: -1


# Below is for 3x3 CLassic ttt game

In [242]:
class Player:
    def __init__(self,name, mark):
        self._name = name
        self._mark = mark

    @property
    def name(self):
        return self._name

    @property
    def mark(self):
        return self._mark

In [264]:
# 3x3 classic tic-tac-toe

class Grid:
    def __init__(self):
        self.n = 3
        self.d = 2 
        self._grid = None
        self.init_grid()

    def init_grid(self):
        _list = []
        for x in range(d):
            _list.append(n)
        _tuple = tuple(_list)
        
        self._grid = np.zeros(_tuple, dtype=int)

    @property
    def grid(self):
        return self._grid

    def place_mark(self, x, y, value):
        self._grid[x][y] = value


    

In [314]:
from typing import List

class Game:
    active_turn = -1
    
    def __init__(self, grid, players: List[str]):
        self._grid = grid
        self._score_grid = None
        if len(players) == 2:
            self._players = [
                Player(players[0], -1), # player 1 is X = -1
                Player(players[1], 1),  # player 2 is O = 1
            ]
        else:
            print("error, there must be only two players")

        if self.get_dim() > 2:
            self.init_score_grid()

    def init_score_grid(self):
        _d = self.get_dim() - 2
        _list = []
        for x in range(_d):
            _list.append(3)
        _tuple = tuple(_list)
        
        self._score_grid = np.zeros(_tuple, dtype=int)
            

    def get_dim(self):
        return self._grid.grid.ndim

    @property
    def score_grid(self):
        return self._score_grid

    @property
    def players(self):
        return self._players

    def switch_turn(self):
        global active_turn
        active_turn *= -1
        return active_turn
    
    def get_player(self):
        return 0 if active_turn == 1 else 1

    def play_move(self, x, y):
        # TODO: check if valid row and column
        
        # check if already placed
        if self._grid.grid[x][y] != 0:
            return "error, already placed"

        active_turn = self.switch_turn()
        print(f"player {self._players[get_player()].name} is placing: {active_turn}")
        self._grid.place_mark(x, y, active_turn)
        print(self._grid.grid)

In [315]:
grid = Grid()
game = Game(grid, ["p1", "p2"]) 
print(game.get_dim())

2


In [316]:
print(game.score_grid)

None


In [333]:
# 0 <= x,y <= 2
import random
x = random.randrange(3)
y = random.randrange(3)
game.play_move(x,y)

player p2 is placing: -1
[[-1 -1 -1]
 [ 1  1  1]
 [ 1 -1 -1]]


In [334]:
print(grid.grid)

[[-1 -1 -1]
 [ 1  1  1]
 [ 1 -1 -1]]


In [335]:
def check_win(matrix):
    """
    - assume grid is a numpy 3x3 matrix

    Need to check:
    - vertical
    - horizontal
    - diagonal (45 degree angle)
    - anti-diagonal (-45 degree angle    
    """
    sums = []


    # Row sums
    row_sums = np.sum(matrix, axis=1)
    print("Row sums:", row_sums)
    
    # Column sums
    col_sums = np.sum(matrix, axis=0)
    print("Column sums:", col_sums) 
    
    # Main diagonal sum (top-left to bottom-right)
    main_diag_sum = np.trace(matrix)
    print("Main diagonal sum:", main_diag_sum)  
    
    # Anti-diagonal sum (top-right to bottom-left)
    anti_diag_sum = np.trace(np.fliplr(matrix))
    print("Anti-diagonal sum:", anti_diag_sum)  


    sums.extend(row_sums)
    sums.extend(col_sums)
    sums.append(main_diag_sum)
    sums.append(anti_diag_sum)


    return sums

In [338]:
all_sum = check_win(grid.grid)

if 3 in all_sum:
    print(f"{game.players[1].name} wins")
elif -3 in all_sum:
    print(f"{game.players[0].name} wins")

Row sums: [-3  3 -1]
Column sums: [ 1 -1 -1]
Main diagonal sum: -1
Anti-diagonal sum: 1
p2 wins


In [414]:
from typing import List

class Game:
    active_turn = -1
    
    def __init__(self, grid, players: List[str]):
        self._grid = grid
        self._score_grid = None
        if len(players) == 2:
            self._players = [
                Player(players[0], -1), # player 1 is X = -1
                Player(players[1], 1),  # player 2 is O = 1
            ]
        else:
            print("error, there must be only two players")

        if self.get_dim() > 2:
            self.init_score_grid()

    def init_score_grid(self):
        _d = self.get_dim() - 2
        _list = []
        for x in range(_d):
            _list.append(3)
        _tuple = tuple(_list)
        
        self._score_grid = np.zeros(_tuple, dtype=int)
            

    def get_dim(self):
        return self._grid.grid.ndim

    @property
    def score_grid(self):
        return self._score_grid

    @property
    def players(self):
        return self._players

    def switch_turn(self):
        global active_turn
        active_turn *= -1
        return active_turn
    
    def get_player(self):
        return 0 if active_turn == 1 else 1

    def play_move(self, x, y):
        # TODO: check if valid row and column
        
        # check if already placed
        if self._grid.grid[x][y] != 0:
            return "error, already placed"

        active_turn = self.switch_turn()
        print(f"player {self._players[get_player()].name} is placing: {active_turn}")
        self._grid.place_mark(x, y, active_turn)
        print(self._grid.grid)

        check_win = self.check_win()
        if check_win:
            return check_win
        

    def check_all_sums(self):
        sums = []
        matrix = self._grid.grid
    
        # Row sums
        row_sums = np.sum(matrix, axis=1)
        print("Row sums:", row_sums)
        
        # Column sums
        col_sums = np.sum(matrix, axis=0)
        print("Column sums:", col_sums) 
        
        # Main diagonal sum (top-left to bottom-right)
        main_diag_sum = np.trace(matrix)
        print("Main diagonal sum:", main_diag_sum)  
        
        # Anti-diagonal sum (top-right to bottom-left)
        anti_diag_sum = np.trace(np.fliplr(matrix))
        print("Anti-diagonal sum:", anti_diag_sum)  
    
    
        sums.extend(row_sums)
        sums.extend(col_sums)
        sums.append(main_diag_sum)
        sums.append(anti_diag_sum)
    
    
        return sums
    
    def check_win(self):
        all_sum = check_win(grid.grid)

        if 3 in all_sum:
            return f"{game.players[1].name} wins"
        elif -3 in all_sum:
            return f"{game.players[0].name} wins"
        

In [415]:
grid = Grid()
game = Game(grid, ["p1", "p2"]) 
print(game.get_dim())

2


In [437]:
# 0 <= x,y <= 2
import random
x = random.randrange(3)
y = random.randrange(3)
game.play_move(x,y)

player p1 is placing: 1
[[-1  1 -1]
 [ 1 -1 -1]
 [ 1  1  1]]
Row sums: [-1 -1  3]
Column sums: [ 1  1 -1]
Main diagonal sum: -1
Anti-diagonal sum: -1


'p2 wins'