# Multi-dimensional ttt (ultimate ttt rules)

In [1]:
import numpy as np
from typing import List


In [61]:
class Grid:
    def __init__(self, d):
        self.w = 3
        self.d = d
        self._grid = None
        self.init_grid()

    def init_grid(self):
        _tuple = tuple([self.w for _ in range(self.d)])
        self._grid = np.zeros(_tuple, dtype=int)

    @property
    def grid(self):
        return self._grid

    def get_w(self):
        return self.w

    def get_d(self):
        return self.d

    def is_valid_position(self, x, y):
        return 0 <= x < self.w and 0 <= y < self.w

    def place_mark(self, x, y, value):
        if self._grid is None:
            raise ValueError("Grid is not initialized")

        if not self.is_valid_position(x, y):
            raise ValueError(f"Position ({x}, {y}) is out of bounds. Valid range: 0-{self.w-1}")

        self._grid[x][y] = value


In [62]:
class Player:
    def __init__(self, name, mark):
        self._name = name
        self._mark = mark

    @property
    def name(self):
        return self._name

    @property
    def mark(self):
        return self._mark


In [79]:
class Game:
    active_turn = -1

    def __init__(self, grid, players: List[str]):
        self._grid = grid
        self._score_grid = None
        self._game_over = False
        if len(players) == 2:
            self._players = [
                Player(players[0], -1),  # player 1 is X = -1
                Player(players[1], 1),  # player 2 is O = 1
            ]
        else:
            raise ValueError("error, there must be only two players")

        # if self.get_dim() > 2:
        #     self.init_score_grid()
        self.sum_to_win = self.get_width() ** (self.get_dim() // 2)

    def init_score_grid(self):
        _d = self.get_dim() - 2
        _list = []
        for _ in range(_d):
            _list.append(3)
        _tuple = tuple(_list)

        self._score_grid = np.zeros(_tuple, dtype=int)

    def get_dim(self):
        return self._grid.get_d()

    def get_width(self):
        return self._grid.get_w()

    # @property
    # def score_grid(self):
    #     return self._score_grid

    @property
    def players(self):
        return self._players

    @property
    def game_over(self):
        return self._game_over

    def switch_turn(self):
        global active_turn
        self.active_turn *= -1
        return self.active_turn

    def get_player(self):
        return 0 if self.active_turn == 1 else 1

    def play_move(self, x, y):
        """play move in a 3x3 grid"""

        # check if already placed
        if self._grid.grid[x][y] != 0:
            # raise ValueError("error, already placed")
            # print("error, already placed")
            return "error, already placed"

        active_turn = self.switch_turn()
        print(
            f"player {self._players[self.get_player()].name} is placing: {active_turn}"
        )
        self._grid.place_mark(x, y, active_turn)
        print(self._grid.grid)

        check_win = self.check_win()
        if check_win:
            self._game_over = True

        # draw
        if 0 not in self._grid.grid and self._game_over is False:
            print("draw")
            self._game_over = True

    def check_all_sums(self):
        sums = []
        matrix = self._grid.grid

        row_sums = np.sum(matrix, axis=1)
        col_sums = np.sum(matrix, axis=0)
        main_diag_sum = np.trace(matrix)
        anti_diag_sum = np.trace(np.fliplr(matrix))

        sums.extend(row_sums)
        sums.extend(col_sums)
        sums.append(main_diag_sum)
        sums.append(anti_diag_sum)

        return sums

    def check_win(self):
        all_sum = self.check_all_sums()

        if 3 in all_sum:
            print(f"{self.players[1].name} wins")
            return True
        elif -3 in all_sum:
            print(f"{self.players[0].name} wins")
            return True


In [90]:

# 3 ^ 6 game
# dimension = 6

grid = Grid(6)
game = Game(grid, ["p1", "p2"]) 
print(game.get_dim())
print(game.get_width())
print(game.sum_to_win)

# while game._game_over is False:
#     x = random.randrange(3)
#     y = random.randrange(3)
#     game.play_move(x,y)


6
3
27


In [105]:
score_grid_4 = np.zeros((3,3)) 
print(score_grid_4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [92]:
score_grid_6 = np.zeros((9,9)) 
print(score_grid_6)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [131]:
def get_score_grid(w,d):
    n = 3**(d//2 - 1)
    print(f"{n}x{n} matrix")
    score_grid_d = np.zeros((n, n)) 
    return score_grid_d


In [132]:
w = 3
d4 = 4
print(get_score_grid(w,d4))

3x3 matrix
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [133]:
d6 = 6
print(get_score_grid(w,d6))

9x9 matrix
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [139]:
# dimension 6
print(np.arange(81).reshape(9, 9))

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


In [138]:
d8 = 8
print(get_score_grid(w,d8))

27x27 matrix
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

In [135]:
d10 = 10
print(get_score_grid(w,d10))

81x81 matrix
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [140]:
def get_score_grid(w,d):
    n = w**(d//2 - 1)
    print(f"{n}x{n} matrix")
    score_grid_d = np.zeros((n, n)) 
    return score_grid_d



def show_index_score_grid(w,d):
    n = w**(d//2 - 1)
    num_of_grids = n * n
    matrix = np.arange(num_of_grids).reshape(n, n)
    return matrix


In [141]:
w = 3
d4 = 4 


print(get_score_grid(w, d4))
print(show_index_score_grid(w, d4))


3x3 matrix
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [142]:
w = 3
d6 = 6
print(get_score_grid(w, d6))
print(show_index_score_grid(w, d6))


9x9 matrix
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


In [144]:
w = 3
d8 = 8
# print(get_score_grid(w, d8))
# print(show_index_score_grid(w, d8))


# -----------------------------------------------------------------

## 2025-07-11, Friday

In [192]:

class Player:
    def __init__(self, name, mark):
        self._name = name
        self._mark = mark

    @property
    def name(self):
        return self._name

    @property
    def mark(self):
        return self._mark


In [214]:
import numpy as np
from typing import List

class Grid:
    def __init__(self, d):
        self.w = 3
        self.d = d
        self._grid = None
        self._score_grid = None
        self.init_grid()
        self.init_score_grid()

    def init_grid(self):
        """
        init grid of zeros depending on the dimension

        ex: 
            - self.d = 2 => _tuple = (3,3)
            - self.d = 4 => _tuple = (3,3,3,3)
        """
        _tuple = tuple([self.w for _ in range(self.d)])
        self._grid = np.zeros(_tuple, dtype=int)

    @property
    def grid(self):
        return self._grid

    def get_w(self):
        return self.w

    def get_d(self):
        return self.d

    def is_valid_position(self, x, y):
        return 0 <= x < self.w and 0 <= y < self.w

    def place_mark(self, x, y, value):
        if self._grid is None:
            raise ValueError("Grid is not initialized")

        if not self.is_valid_position(x, y):
            raise ValueError(f"Position ({x}, {y}) is out of bounds. Valid range: 0-{self.w-1}")

        self._grid[x][y] = value

    
    def init_score_grid(self):
        n = self.w ** (self.d // 2 - 1)
        print(f"{n}x{n} matrix")
        score_grid_d = np.zeros((n, n)) 
        self._score_grid = score_grid_d


    def show_index_grid(self):
        """ get matrix of 3x3 grids """
        n = self.w ** (self.d // 2 - 1)
        num_of_grids = n * n
        matrix = np.arange(num_of_grids).reshape(n, n)
        return matrix

    @property
    def score_grid(self):
        return self._score_grid



In [217]:


grid = Grid(4)

# print(grid)
print(grid.score_grid)

print(grid.show_index_grid())



3x3 matrix
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [223]:

class Game:
    active_turn = -1

    def __init__(self, grid, players: List[str]):
        self.grid = grid
        self._game_over = False

        
        if len(players) == 2:
            # TODO: use dictionary instead of list
            self._players = [
                Player(players[0], -1),  # player 1 is X = -1
                Player(players[1], 1),  # player 2 is O = 1
            ]
        else:
            raise ValueError("error, there must be only two players")

        # if self.get_dim() > 2:
        #     self.init_score_grid()
        self.sum_to_win = self.get_width() ** (self.get_dim() // 2)

    def init_score_grid(self):
        _d = self.get_dim() - 2
        _list = []
        for _ in range(_d):
            _list.append(3)
        _tuple = tuple(_list)

        self._score_grid = np.zeros(_tuple, dtype=int)

    def get_3x3_grid_position(self):
        pass
        

    def get_dim(self):
        return self.grid.get_d()

    def get_width(self):
        return self.grid.get_w()

    @property
    def score_grid(self):
        return self._score_grid

    @property
    def players(self):
        return self._players

    @property
    def game_over(self):
        return self._game_over

    def switch_turn(self):
        global active_turn
        self.active_turn *= -1
        return self.active_turn

    def get_player(self):
        return 0 if self.active_turn == 1 else 1

    def play_move(self, x, y):
        """play move in a 3x3 grid"""

        # check if already placed
        if self.grid.grid[x][y] != 0:
            # raise ValueError("error, already placed")
            # print("error, already placed")
            return "error, already placed"

        active_turn = self.switch_turn()
        print(
            f"player {self._players[self.get_player()].name} is placing: {active_turn}"
        )
        self.grid.place_mark(x, y, active_turn)
        print(self.grid.grid)

        check_win = self.check_win()
        if check_win:
            self._game_over = True

        # draw
        if 0 not in self.grid.grid and self._game_over is False:
            print("draw")
            self._game_over = True

    def check_all_sums(self):
        sums = []
        matrix = self.grid.grid

        row_sums = np.sum(matrix, axis=1)
        col_sums = np.sum(matrix, axis=0)
        main_diag_sum = np.trace(matrix)
        anti_diag_sum = np.trace(np.fliplr(matrix))

        sums.extend(row_sums)
        sums.extend(col_sums)
        sums.append(main_diag_sum)
        sums.append(anti_diag_sum)

        return sums

    def check_win(self):
        all_sum = self.check_all_sums()

        if 3 in all_sum:
            print(f"{self.players[1].name} wins")
            return True
        elif -3 in all_sum:
            print(f"{self.players[0].name} wins")
            return True


In [209]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])

list_result = matrix.tolist()
print(list_result)

result = matrix.flatten().tolist()
print(result)

[[1, 2], [3, 4], [5, 6]]
[1, 2, 3, 4, 5, 6]


In [212]:
grid = Grid(4)
game = Game(grid, ["p1", "p2"]) 

# print(game.grid.grid)
print(game.grid.score_grid)

# print(game.grid.grid)

3x3 matrix
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [222]:
grid = Grid(4)
game = Game(grid, ["p1", "p2"]) 

def get_3x3_grid_position(self):
    pass

3x3 matrix


# it looks like using a matrix that is a list of matrices
# makes getting the position to play complicated if the dimension is greater than 4.

# i think the better approach would be to generate one matrix instead


## nevermind,

- actually, now that i think about it. i think i can combine the two approach.

- keeping what i currently have, a grid that is a list of matrices called game_grid,
- and having a another grid that is a square matrix called position_grid,

- and then creating a method that would take the position in (x,y) in the position grid and convert that to be placed in the game_grid.

  

In [238]:
# width = 3, dimension = 6
# position grid 

position_grid = np.zeros((9,9), dtype=int)
print(position_grid)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [239]:
# width = 3, dimension = 6
# game grid 

game_grid = np.zeros((3,3,3,3,3,3), dtype=int)
print(game_grid[0])

[[[[[0 0 0]
    [0 0 0]
    [0 0 0]]

   [[0 0 0]
    [0 0 0]
    [0 0 0]]

   [[0 0 0]
    [0 0 0]
    [0 0 0]]]


  [[[0 0 0]
    [0 0 0]
    [0 0 0]]

   [[0 0 0]
    [0 0 0]
    [0 0 0]]

   [[0 0 0]
    [0 0 0]
    [0 0 0]]]


  [[[0 0 0]
    [0 0 0]
    [0 0 0]]

   [[0 0 0]
    [0 0 0]
    [0 0 0]]

   [[0 0 0]
    [0 0 0]
    [0 0 0]]]]



 [[[[0 0 0]
    [0 0 0]
    [0 0 0]]

   [[0 0 0]
    [0 0 0]
    [0 0 0]]

   [[0 0 0]
    [0 0 0]
    [0 0 0]]]


  [[[0 0 0]
    [0 0 0]
    [0 0 0]]

   [[0 0 0]
    [0 0 0]
    [0 0 0]]

   [[0 0 0]
    [0 0 0]
    [0 0 0]]]


  [[[0 0 0]
    [0 0 0]
    [0 0 0]]

   [[0 0 0]
    [0 0 0]
    [0 0 0]]

   [[0 0 0]
    [0 0 0]
    [0 0 0]]]]



 [[[[0 0 0]
    [0 0 0]
    [0 0 0]]

   [[0 0 0]
    [0 0 0]
    [0 0 0]]

   [[0 0 0]
    [0 0 0]
    [0 0 0]]]


  [[[0 0 0]
    [0 0 0]
    [0 0 0]]

   [[0 0 0]
    [0 0 0]
    [0 0 0]]

   [[0 0 0]
    [0 0 0]
    [0 0 0]]]


  [[[0 0 0]
    [0 0 0]
    [0 0 0]]

   [[0 0 0]
    [0 0 0]
    [0

In [273]:
# player X place mark at (x=0, y=0)

from tabulate import tabulate

position_grid[0][0] = -1
print(position_grid)



# print(tabulate(position_grid))

[[-1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]]


In [272]:
# then, in the game_grid,
game_grid[0][0][0][0][0][0] = -1

print(tabulate(game_grid[0][0][0][0])) # the first 3x3 grid 
print(game_grid[0])


--  -  -
-1  0  0
 0  0  0
 0  0  0
--  -  -
[[[[[-1  0  0]
    [ 0  0  0]
    [ 0  0  0]]

   [[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]

   [[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]]


  [[[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]

   [[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]

   [[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]]


  [[[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]

   [[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]

   [[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]]]



 [[[[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]

   [[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]

   [[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]]


  [[[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]

   [[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]

   [[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]]


  [[[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]

   [[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]

   [[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]]]



 [[[[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]

   [[ 0  0  0]
    [ 0  0  0]
    [ 0  0  0]]


In [274]:
# moved to version 2